
export type Translations = typeof translations;

export const translations = {
    en: {
        header_title: "NyayaSahayak",
        tab_case_triage: "Case Triage",
        tab_document_analysis: "Document Analysis",
        tab_nyaaybot: "NYAAYBOT",
        tab_legal_tech_hub: "Legal Tech Hub",
        tab_relationship_mapper: "Case Maps",
        tab_justice_timeline: "Justice Timeline",
        tab_judicial_wellness: "Judicial Wellness",
        tab_litigant_happiness: "Litigant Happiness",
        tab_about: "About",
        tab_history: "History",
        case_list_header: "Case Intake Queue",
        case_details_header: "Case Details",
        predict_outcome_button: "Predict Outcome & Priority",
        pii_modal_title: "PII Detected",
        pii_modal_desc: "Potential PII found. Review and confirm redaction before proceeding.",
        pii_modal_confirm: "Confirm & Proceed",
        pii_modal_cancel: "Cancel",
        prediction_result_header: "AI-Powered Triage Analysis",
        priority: "Priority",
        rationale: "Rationale",
        contributing_factors: "Contributing Factors",
        legal_citations: "Legal Citations",
        case_notes: "Case Notes",
        save_notes: "Save Notes",
        nyaaybot_placeholder: "Ask about the Constitution of India...",
        nyaaybot_welcome: "Welcome to NYAAYBOT. How can I assist you with the Constitution of India today?",
        nyaaybot_listening: "Listening...",
        upload_document: "Upload Documents",
        analyze_documents: "Analyze Documents",
        analysis_result: "Analysis Result",
        summary: "Summary",
        severity: "Severity",
        confidence_score: "Confidence Score",
        recommended_court: "Recommended Court",
        legal_entities_found: "Legal Entities Found",
        record_audio: "Record Audio",
        stop_recording: "Stop Recording",
        transcribe_recording: "Transcribe Recording",
        upload_audio_file: "Upload Audio File",
        transcribe_file: "Transcribe File",
        transcription: "Transcription",
        analyze_argument: "Analyze Legal Argument",
        argument_analysis: "Argument Analysis",
        get_walkthrough: "Get Procedural Walkthrough",
        jurisdiction_selection: "Jurisdiction Selection",
        court_type: "Court Type",
        state_union_territory: "State / Union Territory",
        court_number: "Court Number",
        filters: "Filters",
        clear: "Clear",
        search_by_title_number: "Search by Title/Number",
        search_placeholder: "e.g., State vs...",
        from_date: "From Date",
        to_date: "To Date",
        priority_high: "High Priority",
        priority_medium: "Medium Priority",
        priority_low: "Low Priority",
        no_cases_found: "No cases found.",
        try_adjusting_filters: "Try adjusting your filters.",
        petitioner: "Petitioner:",
        respondent: "Respondent:",
        filing_date: "Filing Date:",
        last_hearing: "Last Hearing:",
        invoked_acts: "Invoked Acts:",
        add_notes_placeholder: "Add notes here...",
        select_case_prompt: "Select a case to view details.",
        select_case_instructions: "Choose a case from the queue on the left to get started.",
        year_ago: "year ago",
        years_ago: "years ago",
        month_ago: "month ago",
        months_ago: "months ago",
        day_ago: "day ago",
        days_ago: "days ago",
        hour_ago: "hour ago",
        hours_ago: "hours ago",
        minute_ago: "minute ago",
        minutes_ago: "minutes ago",
        second_ago: "second ago",
        seconds_ago: "seconds ago",
        document_analysis_desc: "Upload documents to harness AI for summarization, entity extraction, and legal insights.",
        drag_and_drop: "Drag & drop files here",
        or_click_to_browse: "or click to browse",
        key_legal_issues: "Key Legal Issues",
        identified_entities: "Identified Entities",
        potential_precedents: "Potential Precedents & Citations",
        moderation_blocked: "Message blocked by content moderation.",
        error_occurred: "An error occurred. Please try again.",
        speech_error: "A speech recognition error occurred. Please try again.",
        voice_input_error: "Could not start voice input. Please try again.",
        mic_access_denied: "Microphone access denied. Please allow microphone access in your browser settings.",
        sources: "Sources:",
        context_files: "Context Files",
        clear_all: "Clear all",
        ask_about_docs_placeholder: "Ask about the document(s)...",
        tool_audio_transcriber: "AI Audio Transcriber",
        tool_argument_analyzer: "AI Legal Argument Analyzer",
        tool_ai_tutor: "Personalized Legal AI Tutor",
        option_1_record_audio: "Option 1: Record Live Audio",
        audio_recorded_ready: "Audio recorded. Ready to transcribe.",
        option_2_upload_audio: "Option 2: Upload an Audio File",
        file_selected: "File selected: ",
        transcription_error: "Error during transcription.",
        transcription_file_error: "Error during transcription of the file.",
        argument_placeholder: "e.g., 'Every human has the right to destroy others dreams'",
        analysis_error: "Error during analysis. The provided argument might be too complex or the service may be temporarily unavailable.",
        strengths: "Strengths",
        weaknesses: "Weaknesses",
        counterarguments: "Counterarguments",
        strategic_recommendations: "Strategic Recommendations",
        personalize_with_docs: "Personalize with Documents (Optional)",
        personalize_with_docs_desc: "Upload legal texts or procedural documents to get a walkthrough based on your specific context.",
        drag_and_drop_browse: "Drag & drop files or click to browse",
        case_walkthrough_title: "{caseType} Case Walkthrough:",
        walkthrough_error: "Error generating walkthrough.",
        case_type_civil: "Civil",
        case_type_criminal: "Criminal",
        case_type_family: "Family",
        case_type_corporate: "Corporate",
        select_case_for_map: "Select a case from the 'Case Triage' tab to see its relationship map.",
        select_case_for_timeline: "Select a case from the 'Case Triage' tab to see its timeline.",
        case_duration_so_far: "Case Duration So Far:",
        days_duration: "{count} days",
        potential_delay_detected: "Potential Delay Detected",
        filing_date_title: "Filing Date",
        last_hearing_date_title: "Last Hearing Date",
        projected_judgment_date_title: "Projected Judgment Date",
        case_load_meter: "Case Load Meter",
        cases_this_month: "cases this month",
        estimated_stress_level: "Estimated Stress Level",
        stress_high: "High",
        stress_moderate: "Moderate",
        stress_low: "Low",
        break_reminder: "Break Reminder",
        break_time_alert: "Time for a break!",
        pause_timer: "Pause Timer",
        start_timer: "Start Timer",
        submit_feedback: "Submit Feedback",
        nps_question: "How likely are you to recommend the judicial process to others? (0-10)",
        additional_comments: "Additional Comments",
        share_experience_placeholder: "Share your experience...",
        submit: "Submit",
        overall_happiness_index: "Overall Happiness Index",
        net_promoter_score: "Net Promoter Score (NPS)",
        thank_you: "Thank You!",
        feedback_submitted_successfully: "Your feedback has been submitted successfully.",
        about_desc: "An AI-first judicial case management platform for the Indian legal system, designed to empower judges and accelerate the delivery of justice.",
        sign_in_with_google: "Sign in with Google",
        sign_up_prompt: "Don't have an account? Sign up",
        sign_in_prompt: "Already have an account? Sign in",
        create_account: "Create Account",
        email_address: "Email Address",
        password: "Password",
        by_signing_in: "By signing in, you agree to our Terms of Service.",
        history_title: "Activity History",
        no_history: "No activity recorded yet.",
        create_new_case: "Create New Case",
        case_title: "Case Title",
        case_number: "Case Number",
        case_summary: "Case Summary",
        case_type: "Case Type",
        acts_involved: "Acts Involved (comma-separated)",
        cancel: "Cancel",
        create: "Create",
        history_case_created: "Created a new case: {title}",
        history_doc_analyzed: "Analyzed document(s): {files}",
    },
    hi: {
        header_title: "न्यायसहायक",
        tab_case_triage: "केस ट्राइएज",
        tab_document_analysis: "दस्तावेज़ विश्लेषण",
        tab_nyaaybot: "न्यायबॉट",
        tab_legal_tech_hub: "विधिक टेक हब",
        tab_relationship_mapper: "केस मैप्स",
        tab_justice_timeline: "न्याय टाइमलाइन",
        tab_judicial_wellness: "न्यायिक कल्याण",
        tab_litigant_happiness: "वादी खुशी सूचकांक",
        tab_about: "बारे में",
        tab_history: "इतिहास",
        case_list_header: "केस इनटेक कतार",
        case_details_header: "केस विवरण",
        predict_outcome_button: "परिणाम और प्राथमिकता की भविष्यवाणी करें",
        pii_modal_title: "पीआईआई का पता चला",
        pii_modal_desc: "संभावित PII मिला। आगे बढ़ने से पहले समीक्षा करें और संशोधन की पुष्टि करें।",
        pii_modal_confirm: "पुष्टि करें और आगे बढ़ें",
        pii_modal_cancel: "रद्द करें",
        prediction_result_header: "एआई-संचालित ट्राइएज विश्लेषण",
        priority: "प्राथमिकता",
        rationale: "तर्क",
        contributing_factors: "योगदान कारक",
        legal_citations: "कानूनी उद्धरण",
        case_notes: "केस नोट्स",
        save_notes: "नोट्स सहेजें",
        nyaaybot_placeholder: "भारत के संविधान के बारे में पूछें...",
        nyaaybot_welcome: "न्यायबॉट में आपका स्वागत है। आज मैं भारत के संविधान के बारे में आपकी कैसे सहायता कर सकता हूँ?",
        nyaaybot_listening: "सुन रहा है...",
        upload_document: "दस्तावेज़ अपलोड करें",
        analyze_documents: "दस्तावेजों का विश्लेषण करें",
        analysis_result: "विश्लेषण परिणाम",
        summary: "सारांश",
        severity: "गंभीरता",
        confidence_score: "आत्मविश्वास स्कोर",
        recommended_court: "अनुशंसित न्यायालय",
        legal_entities_found: "कानूनी संस्थाएं मिलीं",
        record_audio: "ऑडियो रिकॉर्ड करें",
        stop_recording: "रिकॉर्डिंग रोकें",
        transcribe_recording: "रिकॉर्डिंग ट्रांसक्राइब करें",
        upload_audio_file: "ऑडियो फ़ाइल अपलोड करें",
        transcribe_file: "फ़ाइल ट्रांसक्राइब करें",
        transcription: "प्रतिलिपि",
        analyze_argument: "कानूनी तर्क का विश्लेषण करें",
        argument_analysis: "तर्क विश्लेषण",
        get_walkthrough: "प्रक्रियात्मक पूर्वाभ्यास प्राप्त करें",
        jurisdiction_selection: "अधिकार क्षेत्र चयन",
        court_type: "न्यायालय का प्रकार",
        state_union_territory: "राज्य / केंद्र शासित प्रदेश",
        court_number: "न्यायालय संख्या",
        filters: "फ़िल्टर",
        clear: "साफ़ करें",
        search_by_title_number: "शीर्षक/संख्या से खोजें",
        search_placeholder: "जैसे, राज्य बनाम...",
        from_date: "इस तारीख से",
        to_date: "इस तारीख तक",
        priority_high: "उच्च प्राथमिकता",
        priority_medium: "मध्यम प्राथमिकता",
        priority_low: "कम प्राथमिकता",
        no_cases_found: "कोई केस नहीं मिला।",
        try_adjusting_filters: "अपने फ़िल्टर समायोजित करने का प्रयास करें।",
        petitioner: "याचिकाकर्ता:",
        respondent: "प्रतिवादी:",
        filing_date: "दाखिल करने की तारीख:",
        last_hearing: "पिछली सुनवाई:",
        invoked_acts: "लागू अधिनियम:",
        add_notes_placeholder: "यहां नोट्स जोड़ें...",
        select_case_prompt: "विवरण देखने के लिए एक केस चुनें।",
        select_case_instructions: "शुरू करने के लिए बाईं ओर की कतार से एक केस चुनें।",
        year_ago: "वर्ष पहले",
        years_ago: "वर्ष पहले",
        month_ago: "महीना पहले",
        months_ago: "महीने पहले",
        day_ago: "दिन पहले",
        days_ago: "दिन पहले",
        hour_ago: "घंटा पहले",
        hours_ago: "घंटे पहले",
        minute_ago: "मिनट पहले",
        minutes_ago: "मिनट पहले",
        second_ago: "सेकंड पहले",
        seconds_ago: "सेकंड पहले",
        document_analysis_desc: "सारांश, इकाई निष्कर्षण और कानूनी अंतर्दृष्टि के लिए दस्तावेज़ अपलोड करें।",
        drag_and_drop: "फ़ाइलें यहां खींचें और छोड़ें",
        or_click_to_browse: "या ब्राउज़ करने के लिए क्लिक करें",
        key_legal_issues: "मुख्य कानूनी मुद्दे",
        identified_entities: "पहचानी गई इकाइयाँ",
        potential_precedents: "संभावित मिसालें और उद्धरण",
        moderation_blocked: "संदेश सामग्री मॉडरेशन द्वारा अवरुद्ध किया गया।",
        error_occurred: "एक त्रुटि हुई। कृपया पुन: प्रयास करें।",
        speech_error: "एक वाक् पहचान त्रुटि हुई। कृपया पुन: प्रयास करें।",
        voice_input_error: "वॉइस इनपुट शुरू नहीं हो सका। कृपया पुन: प्रयास करें।",
        mic_access_denied: "माइक्रोफ़ोन एक्सेस अस्वीकृत। कृपया अपनी ब्राउज़र सेटिंग्स में माइक्रोफ़ोन एक्सेस की अनुमति दें।",
        sources: "स्रोत:",
        context_files: "संदर्भ फ़ाइलें",
        clear_all: "सभी साफ़ करें",
        ask_about_docs_placeholder: "दस्तावेज़ (दस्तावेज़ों) के बारे में पूछें...",
        tool_audio_transcriber: "एआई ऑडियो ट्रांसक्राइबर",
        tool_argument_analyzer: "एआई कानूनी तर्क विश्लेषक",
        tool_ai_tutor: "व्यक्तिगत कानूनी एआई ट्यूटर",
        option_1_record_audio: "विकल्प 1: लाइव ऑडियो रिकॉर्ड करें",
        audio_recorded_ready: "ऑडियो रिकॉर्ड किया गया। ट्रांसक्राइब करने के लिए तैयार।",
        option_2_upload_audio: "विकल्प 2: एक ऑडियो फ़ाइल अपलोड करें",
        file_selected: "फ़ाइल चयनित: ",
        transcription_error: "ट्रांसक्रिप्शन के दौरान त्रुटि।",
        transcription_file_error: "फ़ाइल के ट्रांसक्रिप्शन के दौरान त्रुटि।",
        argument_placeholder: "जैसे, 'हर इंसान को दूसरों के सपने नष्ट करने का अधिकार है'",
        analysis_error: "विश्लेषण के दौरान त्रुटि। प्रदान किया गया तर्क बहुत जटिल हो सकता है या सेवा अस्थायी रूप से अनुपलब्ध हो सकती है।",
        strengths: "ताकत",
        weaknesses: "कमजोरियाँ",
        counterarguments: "प्रतिवाद",
        strategic_recommendations: "रणनीतिक सिफारिशें",
        personalize_with_docs: "दस्तावेज़ों के साथ वैयक्तिकृत करें (वैकल्पिक)",
        personalize_with_docs_desc: "अपने विशिष्ट संदर्भ के आधार पर पूर्वाभ्यास प्राप्त करने के लिए कानूनी ग्रंथ या प्रक्रियात्मक दस्तावेज़ अपलोड करें।",
        drag_and_drop_browse: "फ़ाइलें खींचें और छोड़ें या ब्राउज़ करने के लिए क्लिक करें",
        case_walkthrough_title: "{caseType} केस पूर्वाभ्यास:",
        walkthrough_error: "पूर्वाभ्यास उत्पन्न करने में त्रुटि।",
        case_type_civil: "सिविल",
        case_type_criminal: "आपराधिक",
        case_type_family: "पारिवारिक",
        case_type_corporate: "कॉर्पोरेट",
        select_case_for_map: "'केस ट्राइएज' टैब से एक केस चुनें ताकि उसका संबंध नक्शा देख सकें।",
        select_case_for_timeline: "'केस ट्राइएज' टैब से एक केस चुनें ताकि उसकी टाइमलाइन देख सकें।",
        case_duration_so_far: "अब तक केस की अवधि:",
        days_duration: "{count} दिन",
        potential_delay_detected: "संभावित देरी का पता चला",
        filing_date_title: "दाखिल करने की तारीख",
        last_hearing_date_title: "पिछली सुनवाई की तारीख",
        projected_judgment_date_title: "अनुमानित निर्णय की तारीख",
        case_load_meter: "केस लोड मीटर",
        cases_this_month: "इस महीने के केस",
        estimated_stress_level: "अनुमानित तनाव स्तर",
        stress_high: "उच्च",
        stress_moderate: "मध्यम",
        stress_low: "कम",
        break_reminder: "ब्रेक रिमाइंडर",
        break_time_alert: "ब्रेक का समय!",
        pause_timer: "टाइमर रोकें",
        start_timer: "टाइमर शुरू करें",
        submit_feedback: "प्रतिक्रिया जमा करें",
        nps_question: "आप दूसरों को न्यायिक प्रक्रिया की सिफारिश करने की कितनी संभावना रखते हैं? (0-10)",
        additional_comments: "अतिरिक्त टिप्पणियाँ",
        share_experience_placeholder: "अपना अनुभव साझा करें...",
        submit: "जमा करें",
        overall_happiness_index: "समग्र खुशी सूचकांक",
        net_promoter_score: "नेट प्रमोटर स्कोर (एनपीएस)",
        thank_you: "धन्यवाद!",
        feedback_submitted_successfully: "आपकी प्रतिक्रिया सफलतापूर्वक जमा कर दी गई है।",
        about_desc: "भारतीय कानूनी प्रणाली के लिए एक एआई-प्रथम न्यायिक केस प्रबंधन मंच, जो न्यायाधीशों को सशक्त बनाने और न्याय वितरण में तेजी लाने के लिए डिज़ाइन किया गया है।",
        sign_in_with_google: "Google से साइन इन करें",
        sign_up_prompt: "खाता नहीं है? साइन अप करें",
        sign_in_prompt: "पहले से ही एक खाता है? साइन इन करें",
        create_account: "खाता बनाएं",
        email_address: "ईमेल पता",
        password: "पासवर्ड",
        by_signing_in: "साइन इन करके, आप हमारी सेवा की शर्तों से सहमत होते हैं।",
        history_title: "गतिविधि इतिहास",
        no_history: "अभी तक कोई गतिविधि दर्ज नहीं की गई है।",
        create_new_case: "नया केस बनाएं",
        case_title: "केस शीर्षक",
        case_number: "केस नंबर",
        case_summary: "केस सारांश",
        case_type: "केस का प्रकार",
        acts_involved: "शामिल अधिनियम (अल्पविराम से अलग)",
        cancel: "रद्द करें",
        create: "बनाएं",
        history_case_created: "एक नया केस बनाया: {title}",
        history_doc_analyzed: "दस्तावेज़ों का विश्लेषण किया: {files}",
    },
    ta: {
        header_title: "நியாயசஹாயக்",
        tab_case_triage: "வழக்கு வகைப்படுத்தல்",
        tab_document_analysis: "ஆவணப் பகுப்பாய்வு",
        tab_nyaaybot: "நியாய்பாட்",
        tab_legal_tech_hub: "சட்ட தொழில்நுட்ப மையம்",
        tab_relationship_mapper: "வழக்கு வரைபடங்கள்",
        tab_justice_timeline: "நீதி காலவரிசை",
        tab_judicial_wellness: "நீதித்துறை ஆரோக்கியம்",
        tab_litigant_happiness: "வழக்கறிஞர் மகிழ்ச்சி குறியீடு",
        tab_about: "பற்றி",
        tab_history: "வரலாறு",
        case_list_header: "வழக்கு உட்கொள்ளல் வரிசை",
        case_details_header: "வழக்கு விவரங்கள்",
        predict_outcome_button: "விளைவு மற்றும் முன்னுரிமையை கணிக்கவும்",
        pii_modal_title: "தனிப்பட்ட அடையாளம் காணக்கூடிய தகவல் கண்டறியப்பட்டது",
        pii_modal_desc: "சாத்தியமான தனிப்பட்ட அடையாளம் காணக்கூடிய தகவல் கண்டறியப்பட்டது. தொடர்வதற்கு முன் மதிப்பாய்வு செய்து உறுதிப்படுத்தவும்.",
        pii_modal_confirm: "உறுதிசெய்து தொடரவும்",
        pii_modal_cancel: "ரத்துசெய்",
        prediction_result_header: "AI-இயங்கும் வகைப்படுத்தல் பகுப்பாய்வு",
        priority: "முன்னுரிமை",
        rationale: "Begründung",
        contributing_factors: "பங்களிக்கும் காரணிகள்",
        legal_citations: "சட்ட மேற்கோள்கள்",
        case_notes: "வழக்கு குறிப்புகள்",
        save_notes: "குறிப்புகளை சேமி",
        nyaaybot_placeholder: "இந்திய அரசியலமைப்பு பற்றி கேட்கவும்...",
        nyaaybot_welcome: "நியாய்பாட்டிற்கு வரவேற்கிறோம். இன்று இந்திய அரசியலமைப்பு பற்றி நான் உங்களுக்கு எப்படி உதவ முடியும்?",
        nyaaybot_listening: "கேட்டுக்கொண்டிருக்கிறது...",
        upload_document: "ஆவணங்களை பதிவேற்றவும்",
        analyze_documents: "ஆவணங்களை பகுப்பாய்வு செய்யவும்",
        analysis_result: "பகுப்பாய்வு முடிவு",
        summary: "சுருக்கம்",
        severity: "கடுமை",
        confidence_score: "நம்பிக்கை மதிப்பெண்",
        recommended_court: "பரிந்துரைக்கப்பட்ட நீதிமன்றம்",
        legal_entities_found: "சட்ட நிறுவனங்கள் கண்டறியப்பட்டன",
        record_audio: "ஆடியோ பதிவு செய்யவும்",
        stop_recording: "பதிவை நிறுத்து",
        transcribe_recording: "பதிவை படியெடுக்கவும்",
        upload_audio_file: "ஆடியோ கோப்பை பதிவேற்றவும்",
        transcribe_file: "கோப்பை படியெடுக்கவும்",
        transcription: "படியெடுத்தல்",
        analyze_argument: "சட்ட வாதத்தை பகுப்பாய்வு செய்யவும்",
        argument_analysis: "வாதப் பகுப்பாய்வு",
        get_walkthrough: "செயல்முறை வழிகாட்டியைப் பெறவும்",
        jurisdiction_selection: "அதிகார வரம்பு தேர்வு",
        court_type: "நீதிமன்ற வகை",
        state_union_territory: "மாநிலம் / யூனியன் பிரதேசம்",
        court_number: "நீதிமன்ற எண்",
        filters: "வடிகட்டிகள்",
        clear: "நீக்கு",
        search_by_title_number: "தலைப்பு/எண் மூலம் தேடவும்",
        search_placeholder: "உதாரணமாக, மாநிலம் எதிர்...",
        from_date: "இருந்து தேதி",
        to_date: "தேதி வரை",
        priority_high: "உயர் முன்னுரிமை",
        priority_medium: "நடுத்தர முன்னுரிமை",
        priority_low: "குறைந்த முன்னுரிமை",
        no_cases_found: "வழக்குகள் எதுவும் இல்லை.",
        try_adjusting_filters: "உங்கள் வடிகட்டிகளை சரிசெய்ய முயற்சிக்கவும்.",
        petitioner: "மனுதாரர்:",
        respondent: "எதிர்மனுதாரர்:",
        filing_date: "தாக்கல் தேதி:",
        last_hearing: "கடைசி விசாரணை:",
        invoked_acts: "செயல்படுத்தப்பட்ட சட்டங்கள்:",
        add_notes_placeholder: "இங்கே குறிப்புகளைச் சேர்க்கவும்...",
        select_case_prompt: "விவரங்களைக் காண ஒரு வழக்கை தேர்ந்தெடுக்கவும்.",
        select_case_instructions: "தொடங்குவதற்கு இடதுபுறத்தில் உள்ள வரிசையிலிருந்து ஒரு வழக்கைத் தேர்வு செய்யவும்.",
        year_ago: "ஆண்டுக்கு முன்",
        years_ago: "ஆண்டுகளுக்கு முன்",
        month_ago: "மாதத்திற்கு முன்",
        months_ago: "மாதங்களுக்கு முன்",
        day_ago: "நாளைக்கு முன்",
        days_ago: "நாட்களுக்கு முன்",
        hour_ago: "மணி நேரத்திற்கு முன்",
        hours_ago: "மணி நேரங்களுக்கு முன்",
        minute_ago: "நிமிடத்திற்கு முன்",
        minutes_ago: "நிமிடங்களுக்கு முன்",
        second_ago: "வினாடிக்கு முன்",
        seconds_ago: "வினாடிகளுக்கு முன்",
        document_analysis_desc: "சுருக்கம், সত্তা নিষ্কাশন மற்றும் আইনগত অন্তর্দৃষ্টির জন্য ஆவணங்களை আপলোড করুন.",
        drag_and_drop: "கோப்புகளை இங்கே இழுத்து விடுங்கள்",
        or_click_to_browse: "அல்லது உலாவ கிளிக் செய்யவும்",
        key_legal_issues: "முக்கிய சட்ட சிக்கல்கள்",
        identified_entities: "அடையாளம் காணப்பட்ட நிறுவனங்கள்",
        potential_precedents: "சாத்தியமான முன்மாதிரிகள் மற்றும் மேற்கோள்கள்",
        moderation_blocked: "செய்தி உள்ளடக்க மதிப்பாய்வால் தடுக்கப்பட்டது.",
        error_occurred: "ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
        speech_error: "பேச்சு அங்கீகாரத்தில் பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
        voice_input_error: "குரல் உள்ளீட்டைத் தொடங்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
        mic_access_denied: "மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது. உங்கள் உலாவி அமைப்புகளில் மைக்ரோஃபோன் அணுகலை அனுமதிக்கவும்.",
        sources: "ஆதாரங்கள்:",
        context_files: "சூழல் கோப்புகள்",
        clear_all: "அனைத்தையும் நீக்கு",
        ask_about_docs_placeholder: "ஆவணம்(கள்) பற்றி கேட்கவும்...",
        tool_audio_transcriber: "AI ஆடியோ டிரான்ஸ்கிரைபர்",
        tool_argument_analyzer: "AI சட்ட வாதப் பகுப்பாய்வி",
        tool_ai_tutor: "தனிப்பயனாக்கப்பட்ட சட்ட AI பயிற்றுவிப்பாளர்",
        option_1_record_audio: "விருப்பம் 1: நேரடி ஆடியோவைப் பதிவுசெய்யவும்",
        audio_recorded_ready: "ஆடியோ பதிவு செய்யப்பட்டது. படியெடுக்கத் தயார்.",
        option_2_upload_audio: "விருப்பம் 2: ஒரு ஆடியோ கோப்பைப் பதிவேற்றவும்",
        file_selected: "கோப்பு தேர்ந்தெடுக்கப்பட்டது: ",
        transcription_error: "படியெடுக்கும்போது பிழை.",
        transcription_file_error: "கோப்பை படியெடுக்கும்போது பிழை.",
        argument_placeholder: "உதாரணமாக, 'ஒவ்வொரு மனிதனுக்கும் மற்றவர்களின் கனவுகளை அழிக்கும் உரிமை உண்டு'",
        analysis_error: "பகுப்பாய்வின் போது பிழை. வழங்கப்பட்ட வாதம் மிகவும் சிக்கலானதாக இருக்கலாம் அல்லது சேவை தற்காலிகமாக கிடைக்காமல் இருக்கலாம்.",
        strengths: "பலங்கள்",
        weaknesses: "பலவீனங்கள்",
        counterarguments: "எதிர்வாதங்கள்",
        strategic_recommendations: "వ్యూహాత్మక సిఫార్సులు",
        personalize_with_docs: "ஆவணங்களுடன் தனிப்பயனாக்கு (விருப்பத்தேர்வு)",
        personalize_with_docs_desc: "உங்கள் குறிப்பிட்ட சூழலின் அடிப்படையில் ஒரு வழிகாட்டியைப் பெற சட்ட நூல்கள் அல்லது நடைமுறை ஆவணங்களை பதிவேற்றவும்.",
        drag_and_drop_browse: "கோப்புகளை இழுத்து விடுங்கள் அல்லது உலாவ கிளிக் செய்யவும்",
        case_walkthrough_title: "{caseType} வழக்கு வழிகாட்டி:",
        walkthrough_error: "வழிகாட்டியை உருவாக்கும்போது பிழை.",
        case_type_civil: "சிவில்",
        case_type_criminal: "குற்றவியல்",
        case_type_family: "குடும்பம்",
        case_type_corporate: "கார்ப்பரேட்",
        select_case_for_map: "அதன் உறவு வரைபடத்தைக் காண 'வழக்கு வகைப்படுத்தல்' தாவலில் இருந்து ஒரு வழக்கை தேர்ந்தெடுக்கவும்.",
        select_case_for_timeline: "அதன் காலவரிசையைக் காண 'வழக்கு வகைப்படுத்தல்' தாவலில் இருந்து ஒரு வழக்கை தேர்ந்தெடுக்கவும்.",
        case_duration_so_far: "இதுவரை வழக்கு காலம்:",
        days_duration: "{count} நாட்கள்",
        potential_delay_detected: "சாத்தியமான தாமதம் கண்டறியப்பட்டது",
        filing_date_title: "தாக்கல் தேதி",
        last_hearing_date_title: "கடைசி விசாரணை தேதி",
        projected_judgment_date_title: "எதிர்பார்க்கப்படும் தீர்ப்பு தேதி",
        case_load_meter: "வழக்கு சுமை மீட்டர்",
        cases_this_month: "இந்த மாத வழக்குகள்",
        estimated_stress_level: "மதிப்பிடப்பட்ட மன அழுத்த நிலை",
        stress_high: "அதிகம்",
        stress_moderate: "மிதமானது",
        stress_low: "குறைவு",
        break_reminder: "இடைவேளை நினைவூட்டல்",
        break_time_alert: "இடைவேளைக்கான நேரம்!",
        pause_timer: "டைமரை இடைநிறுத்து",
        start_timer: "டைமரைத் தொடங்கு",
        submit_feedback: "கருத்துக்களை சமர்ப்பிக்கவும்",
        nps_question: "நீங்கள் மற்றவர்களுக்கு நீதித்துறை செயல்முறையை பரிந்துரைக்க எவ்வளவு வாய்ப்புள்ளது? (0-10)",
        additional_comments: "கூடுதல் கருத்துரைகள்",
        share_experience_placeholder: "உங்கள் அனுபவத்தைப் பகிரவும்...",
        submit: "சமர்ப்பிக்கவும்",
        overall_happiness_index: "ஒட்டுமொத்த மகிழ்ச்சி குறியீடு",
        net_promoter_score: "நிகர ஊக்குவிப்பாளர் மதிப்பெண் (NPS)",
        thank_you: "நன்றி!",
        feedback_submitted_successfully: "உங்கள் கருத்து வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.",
        about_desc: "இந்திய சட்ட அமைப்புக்கான ஒரு AI-முதல் நீதித்துறை வழக்கு மேலாண்மை தளம், நீதிபதிகளை மேம்படுத்துவதற்கும் நீதி வழங்குவதை விரைவுபடுத்துவதற்கும் வடிவமைக்கப்பட்டுள்ளது.",
        sign_in_with_google: "Google மூலம் உள்நுழைக",
        sign_up_prompt: "கணக்கு இல்லையா? பதிவு செய்க",
        sign_in_prompt: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
        create_account: "கணக்கை உருவாக்கு",
        email_address: "மின்னஞ்சல் முகவரி",
        password: "கடவுச்சொல்",
        by_signing_in: "உள்நுழைவதன் மூலம், எங்கள் சேவை விதிமுறைகளை ஒப்புக்கொள்கிறீர்கள்.",
        history_title: "செயல்பாட்டு வரலாறு",
        no_history: "இன்னும் எந்த செயல்பாடும் பதிவு செய்யப்படவில்லை.",
        create_new_case: "புதிய வழக்கை உருவாக்கு",
        case_title: "வழக்கு தலைப்பு",
        case_number: "வழக்கு எண்",
        case_summary: "வழக்கு சுருக்கம்",
        case_type: "வழக்கு வகை",
        acts_involved: "சம்பந்தப்பட்ட சட்டங்கள் (காற்புள்ளியால் பிரிக்கப்பட்டது)",
        cancel: "ரத்துசெய்",
        create: "உருவாக்கு",
        history_case_created: "ஒரு புதிய வழக்கு உருவாக்கப்பட்டது: {title}",
        history_doc_analyzed: "ஆவணங்கள் பகுப்பாய்வு செய்யப்பட்டன: {files}",
    },
    te: {
        header_title: "న్యాయసహాయక్",
        tab_case_triage: "కేసు ట్రయేజ్",
        tab_document_analysis: "పత్ర విశ్లేషణ",
        tab_nyaaybot: "న్యాయ్‌బాట్",
        tab_legal_tech_hub: "లీగల్ టెక్ హబ్",
        tab_relationship_mapper: "కేస్ మ్యాప్స్",
        tab_justice_timeline: "న్యాయం టైమ్‌లైన్",
        tab_judicial_wellness: "జ్యుడీషియల్ వెల్నెస్",
        tab_litigant_happiness: "వ్యాజ్య సంతోష సూచిక",
        tab_about: "గురించి",
        tab_history: "చరిత్ర",
        case_list_header: "కేసు ఇన్‌టేక్ క్యూ",
        case_details_header: "కేసు వివరాలు",
        predict_outcome_button: "ఫలితం & ప్రాధాన్యతను అంచనా వేయండి",
        pii_modal_title: "PII కనుగొనబడింది",
        pii_modal_desc: "సంభావ్య PII కనుగొనబడింది. కొనసాగడానికి ముందు సమీక్షించి, పునఃప్రచురణను నిర్ధారించండి.",
        pii_modal_confirm: "నిర్ధారించి కొనసాగండి",
        pii_modal_cancel: "రద్దు చేయండి",
        prediction_result_header: "AI-ఆధారిత ట్రయేజ్ విశ్లేషణ",
        priority: "ప్రాధాన్యత",
        rationale: "హేతుబద్ధత",
        contributing_factors: "సహకార కారకాలు",
        legal_citations: "చట్టపరమైన ఉల్లేఖనాలు",
        case_notes: "కేసు నోట్స్",
        save_notes: "నోట్స్ సేవ్ చేయండి",
        nyaaybot_placeholder: "భారత రాజ్యాంగం గురించి అడగండి...",
        nyaaybot_welcome: "న్యాయ్‌బాట్‌కు స్వాగతం. ఈ రోజు నేను భారత రాజ్యాంగం గురించి మీకు ఎలా సహాయపడగలను?",
        nyaaybot_listening: "వినడం జరుగుతోంది...",
        upload_document: "పత్రాలను అప్‌లోడ్ చేయండి",
        analyze_documents: "పత్రాలను విశ్లేషించండి",
        analysis_result: "విశ్లేషణ ఫలితం",
        summary: "సారాంశం",
        severity: "తీవ్రత",
        confidence_score: "విశ్వాస స్కోరు",
        recommended_court: "సిఫార్సు చేయబడిన కోర్టు",
        legal_entities_found: "చట్టపరమైన సంస్థలు కనుగొనబడ్డాయి",
        record_audio: "ఆడియో రికార్డ్ చేయండి",
        stop_recording: "రికార్డింగ్ ఆపండి",
        transcribe_recording: "రికార్డింగ్‌ను ట్రాన్స్‌క్రైబ్ చేయండి",
        upload_audio_file: "ఆడియో ఫైల్‌ను అప్‌లోడ్ చేయండి",
        transcribe_file: "ఫైల్‌ను ట్రాన్స్‌క్రైబ్ చేయండి",
        transcription: "ట్రాన్స్క్రిప్షన్",
        analyze_argument: "చట్టపరమైన వాదనను విశ్లేషించండి",
        argument_analysis: "వాదన విశ్లేషణ",
        get_walkthrough: "విధానపరమైన వాక్‌త్రూ పొందండి",
        jurisdiction_selection: "అధికార పరిధి ఎంపిక",
        court_type: "కోర్టు రకం",
        state_union_territory: "రాష్ట్రం / కేంద్రపాలిత ప్రాంతం",
        court_number: "కోర్టు సంఖ్య",
        filters: "ఫిల్టర్లు",
        clear: "క్లియర్",
        search_by_title_number: "శీర్షిక/సంఖ్య ద్వారా శోధించండి",
        search_placeholder: "ఉదా., రాష్ట్రం వర్సెస్...",
        from_date: "తేదీ నుండి",
        to_date: "తేదీ వరకు",
        priority_high: "అధిక ప్రాధాన్యత",
        priority_medium: "మధ్యస్థ ప్రాధాన్యత",
        priority_low: "తక్కువ ప్రాధాన్యత",
        no_cases_found: "కేసులు ఏవీ కనుగొనబడలేదు.",
        try_adjusting_filters: "మీ ఫిల్టర్లను సర్దుబాటు చేయడానికి ప్రయత్నించండి.",
        petitioner: "పిటిషనర్:",
        respondent: "ప్రతివాది:",
        filing_date: "దాఖలు తేదీ:",
        last_hearing: "చివరి విచారణ:",
        invoked_acts: "ఆహ్వానించబడిన చట్టాలు:",
        add_notes_placeholder: "ఇక్కడ గమనికలను జోడించండి...",
        select_case_prompt: "వివరాలను వీక్షించడానికి ఒక కేసును ఎంచుకోండి.",
        select_case_instructions: "ప్రారంభించడానికి ఎడమ వైపున ఉన్న క్యూ నుండి ఒక కేసును ఎంచుకోండి.",
        year_ago: "సంవత్సరం క్రితం",
        years_ago: "సంవత్సరాల క్రితం",
        month_ago: "నెల క్రితం",
        months_ago: "నెలల క్రితం",
        day_ago: "రోజు క్రితం",
        days_ago: "రోజుల క్రితం",
        hour_ago: "గంట క్రితం",
        hours_ago: "గంటల క్రితం",
        minute_ago: "నిమిషం క్రితం",
        minutes_ago: "నిమిషాల క్రితం",
        second_ago: "సెకను క్రితం",
        seconds_ago: "సెకన్ల క్రితం",
        document_analysis_desc: "సారాంశం, సంస్థ వెలికితీత మరియు చట్టపరమైన అంతర్దృష్టుల కోసం పత్రాలను అప్‌లోడ్ చేయండి.",
        drag_and_drop: "ఫైల్‌లను ఇక్కడ లాగి వదలండి",
        or_click_to_browse: "లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
        key_legal_issues: "కీలక చట్టపరమైన సమస్యలు",
        identified_entities: "గుర్తించబడిన సంస్థలు",
        potential_precedents: "సంభావ్య పూర్వాంశాలు & ఉల్లేఖనాలు",
        moderation_blocked: "సందేశం కంటెంట్ నియంత్రణ ద్వారా నిరోధించబడింది.",
        error_occurred: "ఒక లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        speech_error: "ఒక ప్రసంగ గుర్తింపు లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
        voice_input_error: "వాయిస్ ఇన్‌పుట్‌ను ప్రారంభించలేకపోయాము. దయచేసి మళ్లీ ప్రయత్నించండి.",
        mic_access_denied: "మైక్రోఫోన్ యాక్సెస్ నిరాకరించబడింది. దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో మైక్రోఫోన్ యాక్సెస్‌ను అనుమతించండి.",
        sources: "మూలాలు:",
        context_files: "సందర్భ ఫైళ్లు",
        clear_all: "అన్నీ క్లియర్ చేయండి",
        ask_about_docs_placeholder: "పత్రం(ల) గురించి అడగండి...",
        tool_audio_transcriber: "AI ఆడియో ట్రాన్స్‌క్రైబర్",
        tool_argument_analyzer: "AI లీగల్ ఆర్గ్యుమెంట్ ఎనలైజర్",
        tool_ai_tutor: "వ్యక్తిగతీకరించిన లీగల్ AI ట్యూటర్",
        option_1_record_audio: "ఎంపిక 1: లైవ్ ఆడియోను రికార్డ్ చేయండి",
        audio_recorded_ready: "ఆడియో రికార్డ్ చేయబడింది. ట్రాన్స్‌క్రైబ్ చేయడానికి సిద్ధంగా ఉంది.",
        option_2_upload_audio: "ఎంపిక 2: ఒక ఆడియో ఫైల్‌ను అప్‌లోడ్ చేయండి",
        file_selected: "ఫైల్ ఎంచుకోబడింది: ",
        transcription_error: "ట్రాన్స్‌క్రిప్షన్ సమయంలో లోపం.",
        transcription_file_error: "ఫైల్ ట్రాన్స్‌క్రిప్షన్ సమయంలో లోపం.",
        argument_placeholder: "ఉదా., 'ప్రతి మానవుడికి ఇతరుల కలలను నాశనం చేసే హక్కు ఉంది'",
        analysis_error: "విశ్లేషణ సమయంలో లోపం. అందించిన వాదన చాలా క్లిష్టంగా ఉండవచ్చు లేదా సేవ తాత్కాలికంగా అందుబాటులో ఉండకపోవచ్చు.",
        strengths: "బలాలు",
        weaknesses: "బలహీనతలు",
        counterarguments: "ప్రతివాదనలు",
        strategic_recommendations: "వ్యూహాత్మక సిఫార్సులు",
        personalize_with_docs: "పత్రాలతో వ్యక్తిగతీకరించండి (ఐచ్ఛికం)",
        personalize_with_docs_desc: "మీ నిర్దిష్ట సందర్భం ఆధారంగా ఒక వాక్‌త్రూ పొందడానికి చట్టపరమైన పాఠాలు లేదా విధానపరమైన పత్రాలను అప్‌లోడ్ చేయండి.",
        drag_and_drop_browse: "ఫైల్‌లను లాగి వదలండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
        case_walkthrough_title: "{caseType} కేసు వాక్‌త్రూ:",
        walkthrough_error: "వాక్‌త్రూను రూపొందించడంలో లోపం.",
        case_type_civil: "సివిల్",
        case_type_criminal: "క్రిమినల్",
        case_type_family: "కుటుంబం",
        case_type_corporate: "కార్పొరేట్",
        select_case_for_map: "దాని సంబంధిత మ్యాప్‌ను చూడటానికి 'కేసు ట్రయేజ్' ట్యాబ్ నుండి ఒక కేసును ఎంచుకోండి.",
        select_case_for_timeline: "దాని టైమ్‌లైన్‌ను చూడటానికి 'కేసు ట్రయేజ్' ట్యాబ్ నుండి ఒక కేసును ఎంచుకోండి.",
        case_duration_so_far: "ఇప్పటివరకు కేసు వ్యవధి:",
        days_duration: "{count} రోజులు",
        potential_delay_detected: "సంభావ్య జాప్యం కనుగొనబడింది",
        filing_date_title: "దాఖలు తేదీ",
        last_hearing_date_title: "చివరి విచారణ తేదీ",
        projected_judgment_date_title: "అంచనా వేసిన తీర్పు తేదీ",
        case_load_meter: "కేసు లోడ్ మీటర్",
        cases_this_month: "ఈ నెల కేసులు",
        estimated_stress_level: "అంచనా వేసిన ఒత్తిడి స్థాయి",
        stress_high: "అధికం",
        stress_moderate: "మధ్యస్థం",
        stress_low: "తక్కువ",
        break_reminder: "విరామ రిమైండర్",
        break_time_alert: "విరామం కోసం సమయం!",
        pause_timer: "టైమర్‌ను పాజ్ చేయండి",
        start_timer: "టైమర్‌ను ప్రారంభించండి",
        submit_feedback: "అభిప్రాయాన్ని సమర్పించండి",
        nps_question: "మీరు ఇతరులకు న్యాయ ప్రక్రియను ఎంతవరకు సిఫార్సు చేస్తారు? (0-10)",
        additional_comments: "అదనపు వ్యాఖ్యలు",
        share_experience_placeholder: "మీ అనుభవాన్ని పంచుకోండి...",
        submit: "సమర్పించండి",
        overall_happiness_index: "మొత్తం సంతోష సూచిక",
        net_promoter_score: "నెట్ ప్రమోటర్ స్కోర్ (NPS)",
        thank_you: "ధన్యవాదాలు!",
        feedback_submitted_successfully: "మీ అభిప్రాయం విజయవంతంగా సమర్పించబడింది.",
        about_desc: "భారత న్యాయ వ్యవస్థ కోసం ఒక AI-ప్రథమ న్యాయ కేసు నిర్వహణ వేదిక, న్యాయమూర్తులను శక్తివంతం చేయడానికి మరియు న్యాయ పంపిణీని వేగవంతం చేయడానికి రూపొందించబడింది.",
        sign_in_with_google: "Google తో సైన్ ఇన్ చేయండి",
        sign_up_prompt: "ఖాతా లేదా? సైన్ అప్ చేయండి",
        sign_in_prompt: "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
        create_account: "ఖాతాను సృష్టించండి",
        email_address: "ఇమెయిల్ చిరునామా",
        password: "పాస్వర్డ్",
        by_signing_in: "సైన్ ఇన్ చేయడం ద్వారా, మీరు మా సేవా నిబంధనలను అంగీకరిస్తున్నారు.",
        history_title: "కార్యాచరణ చరిత్ర",
        no_history: "ఇంకా కార్యాచరణ ఏదీ రికార్డ్ చేయబడలేదు.",
        create_new_case: "కొత్త కేసును సృష్టించండి",
        case_title: "కేసు శీర్షిక",
        case_number: "కేసు సంఖ్య",
        case_summary: "కేసు సారాంశం",
        case_type: "కేసు రకం",
        acts_involved: "సంబంధిత చట్టాలు (కామాతో వేరు చేయబడ్డాయి)",
        cancel: "రద్దు చేయండి",
        create: "సృష్టించండి",
        history_case_created: "ఒక కొత్త కేసు సృష్టించబడింది: {title}",
        history_doc_analyzed: "పత్రాలు విశ్లేషించబడ్డాయి: {files}",
    },
    bn: {
        header_title: "ন্যায় সহায়ক",
        tab_case_triage: "কেস ট্রায়াজ",
        tab_document_analysis: "নথি বিশ্লেষণ",
        tab_nyaaybot: "ন্যায়বট",
        tab_legal_tech_hub: "লিগ্যাল টেক হাব",
        tab_relationship_mapper: "কেস ম্যাপস",
        tab_justice_timeline: "ন্যায় টাইমলাইন",
        tab_judicial_wellness: "বিচারিক সুস্থতা",
        tab_litigant_happiness: "মামলারী ಸಂತুষ্টি সূচক",
        tab_about: "সম্পর্কে",
        tab_history: "ইতিহাস",
        case_list_header: "কেস ইনটেক কিউ",
        case_details_header: "কেসের বিবরণ",
        predict_outcome_button: "ফলাফল এবং অগ্রাধিকার পূর্বাভাস দিন",
        pii_modal_title: "PII সনাক্ত হয়েছে",
        pii_modal_desc: "সম্ভাব্য PII পাওয়া গেছে। এগিয়ে যাওয়ার আগে পর্যালোচনা এবং সংশোধন নিশ্চিত করুন।",
        pii_modal_confirm: "নিশ্চিত করুন এবং এগিয়ে যান",
        pii_modal_cancel: "বাতিল করুন",
        prediction_result_header: "এআই-চালিত ট্রায়াজ বিশ্লেষণ",
        priority: "অগ্রাধিকার",
        rationale: "যুক্তি",
        contributing_factors: "অবদানকারী কারণ",
        legal_citations: "আইনি উদ্ধৃতি",
        case_notes: "কেস নোট",
        save_notes: "নোট সংরক্ষণ করুন",
        nyaaybot_placeholder: "ভারতের সংবিধান সম্পর্কে জিজ্ঞাসা করুন...",
        nyaaybot_welcome: "ন্যায়বট-এ স্বাগতম। আজ আমি আপনাকে ভারতের সংবিধান সম্পর্কে কীভাবে সাহায্য করতে পারি?",
        nyaaybot_listening: "শুনছে...",
        upload_document: "নথি আপলোড করুন",
        analyze_documents: "নথি বিশ্লেষণ করুন",
        analysis_result: "বিশ্লেষণ ফলাফল",
        summary: "সারসংক্ষেপ",
        severity: "গুরুত্ব",
        confidence_score: "আত্মবিশ্বাস স্কোর",
        recommended_court: "সুপারিশকৃত আদালত",
        legal_entities_found: "আইনি সত্তা পাওয়া গেছে",
        record_audio: "অডিও রেকর্ড করুন",
        stop_recording: "রেকর্ডিং বন্ধ করুন",
        transcribe_recording: "রেকর্ডিং প্রতিলিপি করুন",
        upload_audio_file: "অডিও ফাইল আপলোড করুন",
        transcribe_file: "ফাইল প্রতিলিপি করুন",
        transcription: "প্রতিলিপি",
        analyze_argument: "আইনি যুক্তি বিশ্লেষণ করুন",
        argument_analysis: "যুক্তি বিশ্লেষণ",
        get_walkthrough: "কার্যமுறை ওয়াকথ্রু পান",
        jurisdiction_selection: "এখতিয়ার নির্বাচন",
        court_type: "আদালতের প্রকার",
        state_union_territory: "রাজ্য / কেন্দ্রশাসিত অঞ্চল",
        court_number: "আদালত নম্বর",
        filters: "ফিল্টার",
        clear: "পরিষ্কার",
        search_by_title_number: "শিরোনাম/নম্বর দ্বারা অনুসন্ধান করুন",
        search_placeholder: "যেমন, রাষ্ট্র বনাম...",
        from_date: "তারিখ থেকে",
        to_date: "তারিখ পর্যন্ত",
        priority_high: "উচ্চ অগ্রাধিকার",
        priority_medium: "মাঝারি অগ্রাধিকার",
        priority_low: "নিম্ন অগ্রাধিকার",
        no_cases_found: "কোনো কেস পাওয়া যায়নি।",
        try_adjusting_filters: "আপনার ফিল্টারগুলি সামঞ্জস্য করার চেষ্টা করুন।",
        petitioner: "আবেদনকারী:",
        respondent: "উত্তরদাতা:",
        filing_date: "দাখিলের তারিখ:",
        last_hearing: "শেষ শুনানি:",
        invoked_acts: "আহ্বান করা আইন:",
        add_notes_placeholder: "এখানে নোট যোগ করুন...",
        select_case_prompt: "বিস্তারিত দেখতে একটি কেস নির্বাচন করুন।",
        select_case_instructions: "শুরু করতে বাম দিকের কিউ থেকে একটি কেস বেছে নিন।",
        year_ago: "বছর আগে",
        years_ago: "বছর আগে",
        month_ago: "মাস আগে",
        months_ago: "মাস আগে",
        day_ago: "দিন আগে",
        days_ago: "দিন আগে",
        hour_ago: "ঘন্টা আগে",
        hours_ago: "ঘন্টা আগে",
        minute_ago: "মিনিট আগে",
        minutes_ago: "মিনিট আগে",
        second_ago: "সেকেন্ড আগে",
        seconds_ago: "সেকেন্ড আগে",
        document_analysis_desc: "সারসংক্ষেপ, সত্তা নিষ্কাশন এবং আইনগত অন্তর্দৃষ্টির জন্য নথি আপলোড করুন।",
        drag_and_drop: "এখানে ফাইল টেনে আনুন",
        or_click_to_browse: "অথবা ব্রাউজ করতে ক্লিক করুন",
        key_legal_issues: "মূল আইনি বিষয়",
        identified_entities: "শনাক্তকৃত সত্তা",
        potential_precedents: "সম্ভাব্য নজির ও উদ্ধৃতি",
        moderation_blocked: "বার্তাটি বিষয়বস্তু মডারেশন দ্বারা ব্লক করা হয়েছে।",
        error_occurred: "একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        speech_error: "একটি বক্তৃতা শনাক্তকরণ ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
        voice_input_error: "ভয়েস ইনপুট শুরু করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
        mic_access_denied: "মাইক্রোফোন অ্যাক্সেস अस्वीकार করা হয়েছে। অনুগ্রহ করে আপনার ব্রাউজার সেটিংসে মাইক্রোফোন অ্যাক্সেসের অনুমতি দিন।",
        sources: "উৎস:",
        context_files: "প্রসঙ্গ ফাইল",
        clear_all: "সব মুছে ফেলুন",
        ask_about_docs_placeholder: "নথি(গুলি) সম্পর্কে জিজ্ঞাসা করুন...",
        tool_audio_transcriber: "এআই অডিও ট্রান্সক্রাইবার",
        tool_argument_analyzer: "এআই আইনি যুক্তি বিশ্লেষক",
        tool_ai_tutor: "ব্যক্তিগতকৃত আইনি এআই টিউটর",
        option_1_record_audio: "বিকল্প ১: লাইভ অডিও রেকর্ড করুন",
        audio_recorded_ready: "অডিও রেকর্ড করা হয়েছে। প্রতিলিপি করার জন্য প্রস্তুত।",
        option_2_upload_audio: "বিকল্প ২: একটি অডিও ফাইল আপলোড করুন",
        file_selected: "ফাইল নির্বাচিত: ",
        transcription_error: "প্রতিলিপি করার সময় ত্রুটি।",
        transcription_file_error: "ফাইলের প্রতিলিপি করার সময় ত্রুটি।",
        argument_placeholder: "যেমন, 'প্রতিটি মানুষের অন্যদের স্বপ্ন ধ্বংস করার অধিকার আছে'",
        analysis_error: "বিশ্লেষণের সময় ত্রুটি। প্রদত্ত যুক্তিটি খুব জটিল হতে পারে বা পরিষেবাটি সাময়িকভাবে अनुपलब्ध থাকতে পারে।",
        strengths: "শক্তি",
        weaknesses: "দুর্বলতা",
        counterarguments: "প্রতিযুক্তি",
        strategic_recommendations: "কৌশলগত সুপারিশ",
        personalize_with_docs: "নথি দিয়ে ব্যক্তিগতকরণ করুন (ঐচ্ছিক)",
        personalize_with_docs_desc: "আপনার নির্দিষ্ট প্রসঙ্গের উপর ভিত্তি করে একটি ওয়াকথ্রু পেতে আইনি পাঠ্য বা পদ্ধতিগত নথি আপলোড করুন।",
        drag_and_drop_browse: "ফাইল টেনে আনুন বা ব্রাউজ করতে ক্লিক করুন",
        case_walkthrough_title: "{caseType} কেস ওয়াকথ্রু:",
        walkthrough_error: "ওয়াকথ্রু তৈরি করার সময় ত্রুটি।",
        case_type_civil: "দেওয়ানি",
        case_type_criminal: "ফৌজদারি",
        case_type_family: "পারিবারিক",
        case_type_corporate: "কর্পোরেট",
        select_case_for_map: "এর সম্পর্ক মানচিত্র দেখতে 'কেস ট্রায়াজ' ট্যাব থেকে একটি কেস নির্বাচন করুন।",
        select_case_for_timeline: "এর টাইমলাইন দেখতে 'কেস ট্রায়াজ' ট্যাব থেকে একটি কেস নির্বাচন করুন।",
        case_duration_so_far: "এখন পর্যন্ত মামলার সময়কাল:",
        days_duration: "{count} দিন",
        potential_delay_detected: "সম্ভাব্য বিলম্ব সনাক্ত হয়েছে",
        filing_date_title: "দাখিলের তারিখ",
        last_hearing_date_title: "শেষ শুনানির তারিখ",
        projected_judgment_date_title: "প্রত্যাশিত রায়ের তারিখ",
        case_load_meter: "কেস লোড মিটার",
        cases_this_month: "এই মাসের কেস",
        estimated_stress_level: "আনুমানিক মানসিক চাপ স্তর",
        stress_high: "উচ্চ",
        stress_moderate: "মাঝারি",
        stress_low: "নিম্ন",
        break_reminder: "বিরতি অনুস্মারক",
        break_time_alert: "বিরতির সময়!",
        pause_timer: "টাইমার থামান",
        start_timer: "টাইমার শুরু করুন",
        submit_feedback: "প্রতিক্রিয়া জমা দিন",
        nps_question: "আপনি অন্যদের কাছে বিচারিক প্রক্রিয়াটি সুপারিশ করার কতটা সম্ভাবনা রাখেন? (0-10)",
        additional_comments: "অতিরিক্ত মন্তব্য",
        share_experience_placeholder: "আপনার অভিজ্ঞতা শেয়ার করুন...",
        submit: "জমা দিন",
        overall_happiness_index: "সামগ্রিক সন্তুষ্টি সূচক",
        net_promoter_score: "নেট প্রমোটার স্কোর (NPS)",
        thank_you: "ধন্যবাদ!",
        feedback_submitted_successfully: "আপনার প্রতিক্রিয়া সফলভাবে জমা দেওয়া হয়েছে।",
        about_desc: "ভারতীয় আইন ব্যবস্থার জন্য একটি এআই-প্রথম বিচারিক কেস ম্যানেজমেন্ট প্ল্যাটফর্ম, যা বিচারকদের ক্ষমতায়ন এবং ন্যায়বিচার প্রদানকে ত্বরান্বিত করার জন্য ডিজাইন করা হয়েছে।",
        sign_in_with_google: "Google দিয়ে সাইন ইন করুন",
        sign_up_prompt: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        sign_in_prompt: "ইতিমধ্যেই একটি অ্যাকাউন্ট আছে? সাইন ইন করুন",
        create_account: "অ্যাকাউন্ট তৈরি করুন",
        email_address: "ইমেল ঠিকানা",
        password: "পাসওয়ার্ড",
        by_signing_in: "সাইন ইন করার মাধ্যমে, আপনি আমাদের পরিষেবার শর্তাবলীতে সম্মত হন।",
        history_title: "কার্যকলাপ ইতিহাস",
        no_history: "এখনও কোনো কার্যকলাপ রেকর্ড করা হয়নি।",
        create_new_case: "নতুন কেস তৈরি করুন",
        case_title: "মামলার শিরোনাম",
        case_number: "মামলা নম্বর",
        case_summary: "মামলার সারসংক্ষেপ",
        case_type: "মামলার ধরণ",
        acts_involved: "জড়িত আইন (কমা দ্বারা পৃথক)",
        cancel: "বাতিল করুন",
        create: "তৈরি করুন",
        history_case_created: "একটি নতুন কেস তৈরি করা হয়েছে: {title}",
        history_doc_analyzed: "নথি বিশ্লেষণ করা হয়েছে: {files}",
    }
};
