
export const enTranslations = {
    header_title: "NyayaSahayak",
    tab_case_triage: "Case Triage",
    tab_document_analysis: "Document Analysis",
    tab_nyayabot: "NYAYABOT",
    tab_legal_tech_hub: "Legal Tech Hub",
    tab_relationship_mapper: "Case Maps",
    tab_justice_timeline: "Justice Timeline",
    tab_judicial_wellness: "Judicial Wellness",
    tab_litigant_happiness: "Litigant Happiness",
    tab_quantum_fingerprinting: "Document Integrity",
    tab_about: "About",
    tab_history: "History",
    case_list_header: "Case Intake Queue",
    case_details_header: "Case Details",
    predict_outcome_button: "Predict Outcome & Priority",
    pii_modal_title: "PII Detected",
    pii_modal_desc: "Potential PII found. Review and confirm redaction before proceeding.",
    pii_modal_confirm: "Confirm & Proceed",
    pii_modal_cancel: "Cancel",
    prediction_result_header: "AI-Powered Triage Analysis",
    priority: "Priority",
    rationale: "Rationale",
    contributing_factors: "Contributing Factors",
    legal_citations: "Legal Citations",
    case_notes: "Case Notes",
    save_notes: "Save Notes",
    nyayabot_placeholder: "Ask about the Constitution of India...",
    nyayabot_welcome: "Hello! I'm NYAYABOT, your friendly guide to the Constitution of India. I'm here to help explain complex topics in a simple way. What would you like to know?",
    nyayabot_listening: "Listening...",
    upload_document: "Upload Documents",
    analyze_documents: "Analyze Documents",
    analysis_result: "Analysis Result",
    summary: "Summary",
    severity: "Severity",
    confidence_score: "Confidence Score",
    recommended_court: "Recommended Court",
    legal_entities_found: "Legal Entities Found",
    record_audio: "Record Audio",
    stop_recording: "Stop Recording",
    transcribe_recording: "Transcribe Recording",
    upload_audio_file: "Upload Audio File",
    transcribe_file: "Transcribe File",
    transcription: "Transcription",
    analyze_argument: "Analyze Legal Argument",
    argument_analysis: "Argument Analysis",
    get_walkthrough: "Get Procedural Walkthrough",
    jurisdiction_selection: "Jurisdiction Selection",
    court_type: "Court Type",
    state_union_territory: "State / Union Territory",
    court_number: "Court Number",
    filters: "Filters",
    clear: "Clear",
    search_by_title_number: "Search Title, Number, Petitioner, Respondent...",
    search_placeholder: "e.g., State vs...",
    from_date: "From Date",
    to_date: "To Date",
    priority_high: "High Priority",
    priority_medium: "Medium Priority",
    priority_low: "Low Priority",
    no_cases_found: "No cases found.",
    try_adjusting_filters: "Try adjusting your filters.",
    petitioner: "Petitioner:",
    respondent: "Respondent:",
    filing_date: "Filing Date:",
    last_hearing: "Last Hearing:",
    invoked_acts: "Invoked Acts:",
    add_notes_placeholder: "Add notes here...",
    select_case_prompt: "Select a case to view details.",
    select_case_instructions: "Choose a case from the queue on the left to get started.",
    year_ago: "year ago",
    years_ago: "years ago",
    month_ago: "month ago",
    months_ago: "months ago",
    day_ago: "day ago",
    days_ago: "days ago",
    hour_ago: "hour ago",
    hours_ago: "hours ago",
    minute_ago: "minute ago",
    minutes_ago: "minutes ago",
    second_ago: "second ago",
    seconds_ago: "seconds ago",
    document_analysis_desc: "Upload documents to harness AI for summarization, entity extraction, and legal insights.",
    drag_and_drop: "Drag & drop files here",
    or_click_to_browse: "or click to browse",
    key_legal_issues: "Key Legal Issues",
    identified_entities: "Identified Entities",
    potential_precedents: "Potential Precedents & Citations",
    moderation_blocked: "Message blocked by content moderation.",
    error_occurred: "An error occurred. Please try again.",
    speech_error: "A speech recognition error occurred. Please try again.",
    voice_input_error: "Could not start voice input. Please try again.",
    mic_access_denied: "Microphone access denied. Please allow microphone access in your browser settings.",
    sources: "Sources:",
    context_files: "Context Files",
    clear_all: "Clear all",
    ask_about_docs_placeholder: "Ask about the document(s)...",
    tool_audio_transcriber: "AI Audio Transcriber",
    tool_argument_analyzer: "AI Legal Argument Analyzer",
    tool_ai_tutor: "Personalized Legal AI Tutor",
    option_1_record_audio: "Option 1: Record Live Audio",
    audio_recorded_ready: "Audio recorded. Ready to transcribe.",
    option_2_upload_audio: "Option 2: Upload an Audio File",
    file_selected: "File selected: ",
    transcription_error: "Error during transcription.",
    transcription_file_error: "Error during transcription of the file.",
    argument_placeholder: "e.g., 'Every child has the fundamental right to education'",
    analysis_error: "Error during analysis. The provided argument might be too complex or the service may be temporarily unavailable.",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    counterarguments: "Counterarguments",
    strategic_recommendations: "Strategic Recommendations",
    personalize_with_docs: "Personalize with Documents (Optional)",
    personalize_with_docs_desc: "Upload legal texts or procedural documents to get a walkthrough based on your specific context.",
    drag_and_drop_browse: "Drag & drop files or click to browse",
    case_walkthrough_title: "{caseType} Case Walkthrough:",
    walkthrough_error: "Error generating walkthrough.",
    case_type_civil: "Civil",
    case_type_criminal: "Criminal",
    case_type_family: "Family",
    case_type_corporate: "Corporate",
    select_case_for_map: "Select a case from the 'Case Triage' tab to see its relationship map.",
    select_case_for_timeline: "Select a case from the 'Case Triage' tab to see its timeline.",
    select_case_for_fingerprint: "Select a case from the 'Case Triage' tab to generate its document fingerprint.",
    case_duration_so_far: "Case Duration So Far:",
    days_duration: "{count} days",
    potential_delay_detected: "Potential Delay Detected",
    filing_date_title: "Filing Date",
    last_hearing_date_title: "Last Hearing Date",
    projected_judgment_date_title: "Projected Judgment Date",
    case_load_meter: "Case Load Meter",
    cases_this_month: "cases this month",
    estimated_stress_level: "Estimated Stress Level",
    stress_high: "High",
    stress_moderate: "Moderate",
    stress_low: "Low",
    break_reminder: "Break Reminder",
    break_time_alert: "Time for a break!",
    pause_timer: "Pause Timer",
    start_timer: "Start Timer",
    custom_timer_duration: "Custom Duration",
    set: "Set",
    reset: "Reset",
    submit_feedback: "Submit Feedback",
    nps_question: "How likely are you to recommend the judicial process to others? (0-10)",
    additional_comments: "Additional Comments",
    share_experience_placeholder: "Share your experience...",
    submit: "Submit",
    overall_happiness_index: "Overall Happiness Index",
    net_promoter_score: "Net Promoter Score (NPS)",
    thank_you: "Thank You!",
    feedback_submitted_successfully: "Your feedback has been submitted successfully.",
    about_desc: "An AI-first judicial case management platform for the Indian legal system, designed to empower judges and accelerate the delivery of justice.",
    sign_in_with_google: "Sign in with Google",
    sign_up_prompt: "Don't have an account? Sign up",
    sign_in_prompt: "Already have an account? Sign in",
    create_account: "Create Account",
    email_address: "Email Address",
    password: "Password",
    by_signing_in: "By signing in, you agree to our Terms of Service.",
    history_title: "Activity History",
    no_history: "No activity recorded yet.",
    create_new_case: "Create New Case",
    case_title: "Case Title",
    case_number: "Case Number",
    case_summary: "Case Summary",
    case_type: "Case Type",
    acts_involved: "Acts Involved (comma-separated)",
    cancel: "Cancel",
    create: "Create",
    history_case_created: "Created a new case: {title}",
    history_doc_analyzed: "Analyzed document(s): {files}",
    history_quantum_fingerprinted: "Generated document fingerprint for case: {caseNumber}",
    history_quantum_fingerprinted_generic: "Generated a document fingerprint.",
    history_document_verified: "Verified document integrity. Result: {result}",
    quantum_fingerprinting_desc: "Generate a unique cryptographic hash to verify document integrity and detect tampering.",
    generate_fingerprint: "Generate Document Fingerprint",
    generating_fingerprint: "Generating Fingerprint...",
    quantum_fingerprint_report: "Document Fingerprint Integrity Report",
    quantum_hash: "Cryptographic Hash",
    integrity_status: "Integrity Status",
    anomalies_detected: "Anomalies Detected",
    verification_timestamp: "Verification Timestamp",
    status_ok: "Verified & Secure",
    status_compromised: "Potential Tampering Detected",
    none_detected: "None Detected",
    verify_integrity_title: "Verify Document Integrity",
    paste_hash_placeholder: "Paste original fingerprint hash here",
    paste_content_placeholder: "Paste full document content here to verify",
    paste_content_for_fingerprint: "Paste full document content here to generate fingerprint",
    verify_button: "Verify Integrity",
    verifying_button: "Verifying...",
    verification_result_title: "Verification Result",
    verification_match: "Match: Document content matches the original fingerprint. No tampering detected.",
    verification_mismatch: "Mismatch: Document content does not match the original fingerprint. Tampering detected.",
    verification_error: "Error: Verification could not be completed.",
    doc_analysis_mode_analysis: "Analyze Documents",
    doc_analysis_mode_integrity: "Verify Document Integrity",
    chat_history: "Chat History",
    new_chat: "New Chat",
    clear_chat: "Clear Chat",
    delete_chat: "Delete",
    no_chat_history: "No saved chats.",
    confirm_clear: "Are you sure you want to clear the current chat?",
    clear_history: "Clear History",
    confirm_clear_history: "Are you sure you want to clear all activity history?",
};

export const translations = {
    en: enTranslations,
    hi: enTranslations,
    ta: enTranslations,
    te: enTranslations,
    bn: enTranslations,
    mr: enTranslations,
    gu: enTranslations,
    kn: enTranslations,
    ml: enTranslations,
    pa: enTranslations,
    or: enTranslations,
    sa: enTranslations,
    ur: enTranslations,
    as: enTranslations,
    mai: enTranslations,
    sat: enTranslations,
    ks: enTranslations,
    kok: enTranslations,
    sd: enTranslations,
    doi: enTranslations,
    mni: enTranslations,
    brx: enTranslations,
    ne: enTranslations,
};

export type Translations = typeof translations;
