
import { Case } from '../types';
import { Language } from '../hooks/useLocalization';

const mockCasesEn: Case[] = [
    {
        id: '1',
        title: "State of Maharashtra vs. Raj Sharma",
        caseNumber: "CR/0255/2023",
        petitioner: "State of Maharashtra",
        respondent: "Raj Sharma",
        invokedActs: ["Indian Penal Code, 1860, Sec 302", "Arms Act, 1959, Sec 25"],
        filingDate: "2023-01-15",
        lastHearingDate: "2024-05-20",
        complexityScore: 8.5,
        summary: "A criminal case involving charges of murder and illegal possession of firearms. The prosecution alleges that the respondent, Raj Sharma, was involved in a fatal shooting. Key evidence includes eyewitness testimony and forensic reports.",
        pii: {
            "Raj Sharma": "[REDACTED_PERSON]",
            "CR/0255/2023": "[REDACTED_CASE_ID]",
        },
        priority: 'High',
        caseType: 'Criminal',
    },
    {
        id: '2',
        title: "Priya Singh vs. ABC Corporation",
        caseNumber: "CIV/1089/2022",
        petitioner: "Priya Singh",
        respondent: "ABC Corporation",
        invokedActs: ["Consumer Protection Act, 2019", "Contract Act, 1872"],
        filingDate: "2022-11-02",
        lastHearingDate: "2024-06-10",
        complexityScore: 6.2,
        summary: "A civil suit filed by Priya Singh against ABC Corporation for breach of contract and providing deficient services. The petitioner claims financial damages due to the respondent's failure to deliver on a service agreement.",
        pii: {
            "Priya Singh": "[REDACTED_PERSON]",
            "ABC Corporation": "[REDACTED_ORGANIZATION]",
        },
        priority: 'Medium',
        caseType: 'Civil',
    },
    {
        id: '3',
        title: "Union of India vs. Environmental Activists Group",
        caseNumber: "PIL/0045/2024",
        petitioner: "Union of India",
        respondent: "Environmental Activists Group",
        invokedActs: ["National Green Tribunal Act, 2010", "Environmental Protection Act, 1986"],
        filingDate: "2024-02-10",
        lastHearingDate: "2024-07-01",
        complexityScore: 9.1,
        summary: "A Public Interest Litigation (PIL) concerning the environmental clearance for a major infrastructure project. The respondent group has challenged the clearance, citing potential ecological damage.",
        priority: 'High',
        caseType: 'PIL',
    },
    {
        id: '4',
        title: "Anjali Verma vs. Sunil Verma",
        caseNumber: "FAM/0312/2023",
        petitioner: "Anjali Verma",
        respondent: "Sunil Verma",
        invokedActs: ["Hindu Marriage Act, 1955", "Domestic Violence Act, 2005"],
        filingDate: "2023-08-25",
        lastHearingDate: "2024-06-28",
        complexityScore: 5.5,
        summary: "A family court matter regarding a petition for divorce and allegations of domestic violence. The case involves matters of child custody and alimony.",
        pii: {
            "Anjali Verma": "[REDACTED_PERSON]",
            "Sunil Verma": "[REDACTED_PERSON]",
        },
        priority: 'Low',
        caseType: 'Divorce',
    },
];

const mockCasesHi: Case[] = [
    {
        id: '1',
        title: "महाराष्ट्र राज्य बनाम राज शर्मा",
        caseNumber: "CR/0255/2023",
        petitioner: "महाराष्ट्र राज्य",
        respondent: "राज शर्मा",
        invokedActs: ["भारतीय दंड संहिता, 1860, धारा 302", "शस्त्र अधिनियम, 1959, धारा 25"],
        filingDate: "2023-01-15",
        lastHearingDate: "2024-05-20",
        complexityScore: 8.5,
        summary: "हत्या और आग्नेयास्त्रों के अवैध कब्जे के आरोपों से जुड़ा एक आपराधिक मामला। अभियोजन पक्ष का आरोप है कि प्रतिवादी, राज शर्मा, एक घातक गोलीबारी में शामिल था। मुख्य सबूतों में प्रत्यक्षदर्शी गवाही और फोरेंसिक रिपोर्ट शामिल हैं।",
        pii: {
            "राज शर्मा": "[REDACTED_PERSON]",
            "CR/0255/2023": "[REDACTED_CASE_ID]",
        },
        priority: 'High',
        caseType: 'Criminal',
    },
    {
        id: '2',
        title: "प्रिया सिंह बनाम एबीसी कॉर्पोरेशन",
        caseNumber: "CIV/1089/2022",
        petitioner: "प्रिया सिंह",
        respondent: "एबीसी कॉर्पोरेशन",
        invokedActs: ["उपभोक्ता संरक्षण अधिनियम, 2019", "अनुबंध अधिनियम, 1872"],
        filingDate: "2022-11-02",
        lastHearingDate: "2024-06-10",
        complexityScore: 6.2,
        summary: "प्रिया सिंह द्वारा एबीसी कॉर्पोरेशन के खिलाफ अनुबंध के उल्लंघन और दोषपूर्ण सेवाएं प्रदान करने के लिए दायर एक दीवानी मुकदमा। याचिकाकर्ता का दावा है कि प्रतिवादी द्वारा सेवा समझौते पर खरा न उतरने के कारण वित्तीय क्षति हुई है।",
        pii: {
            "प्रिया सिंह": "[REDACTED_PERSON]",
            "एबीसी कॉर्पोरेशन": "[REDACTED_ORGANIZATION]",
        },
        priority: 'Medium',
        caseType: 'Civil',
    },
    {
        id: '3',
        title: "भारत संघ बनाम पर्यावरण कार्यकर्ता समूह",
        caseNumber: "PIL/0045/2024",
        petitioner: "भारत संघ",
        respondent: "पर्यावरण कार्यकर्ता समूह",
        invokedActs: ["राष्ट्रीय हरित अधिकरण अधिनियम, 2010", "पर्यावरण संरक्षण अधिनियम, 1986"],
        filingDate: "2024-02-10",
        lastHearingDate: "2024-07-01",
        complexityScore: 9.1,
        summary: "एक प्रमुख बुनियादी ढांचा परियोजना के लिए पर्यावरण मंजूरी से संबंधित एक जनहित याचिका (पीआईएल)। प्रतिवादी समूह ने संभावित पारिस्थितिक क्षति का हवाला देते हुए मंजूरी को चुनौती दी है।",
        priority: 'High',
        caseType: 'PIL',
    },
    {
        id: '4',
        title: "अंजलि वर्मा बनाम सुनील वर्मा",
        caseNumber: "FAM/0312/2023",
        petitioner: "अंजलि वर्मा",
        respondent: "सुनील वर्मा",
        invokedActs: ["हिंदू विवाह अधिनियम, 1955", "घरेलू हिंसा अधिनियम, 2005"],
        filingDate: "2023-08-25",
        lastHearingDate: "2024-06-28",
        complexityScore: 5.5,
        summary: "तलाक की याचिका और घरेलू हिंसा के आरोपों से संबंधित एक पारिवारिक अदालत का मामला। इस मामले में बच्चे की हिरासत और गुजारा भत्ता के मामले शामिल हैं।",
        pii: {
            "अंजलि वर्मा": "[REDACTED_PERSON]",
            "सुनील वर्मा": "[REDACTED_PERSON]",
        },
        priority: 'Low',
        caseType: 'Divorce',
    },
];

const mockCasesTa: Case[] = [
    {
        id: '1',
        title: "மகாராஷ்டிரா அரசு vs. ராஜ் சர்மா",
        caseNumber: "CR/0255/2023",
        petitioner: "மகாராஷ்டிரா அரசு",
        respondent: "ராஜ் சர்மா",
        invokedActs: ["இந்திய தண்டனைச் சட்டம், 1860, பிரிவு 302", "ஆயுதச் சட்டம், 1959, பிரிவு 25"],
        filingDate: "2023-01-15",
        lastHearingDate: "2024-05-20",
        complexityScore: 8.5,
        summary: "கொலை மற்றும் சட்டவிரோதமாக துப்பாக்கிகளை வைத்திருந்த குற்றச்சாட்டுகளை உள்ளடக்கிய ஒரு கிரிமினல் வழக்கு. பிரதிவாதி, ராஜ் சர்மா, ஒரு கொடிய துப்பாக்கிச் சூட்டில் ஈடுபட்டதாக அரசுத் தரப்பு குற்றம் சாட்டுகிறது. முக்கிய ஆதாரங்களில் நேரடி சாட்சியம் மற்றும் தடயவியல் அறிக்கைகள் அடங்கும்.",
        pii: { "ராஜ் சர்மா": "[REDACTED_PERSON]" },
        priority: 'High',
        caseType: 'Criminal',
    },
    {
        id: '2',
        title: "பிரியா சிங் vs. ஏபிசி கார்ப்பரேஷன்",
        caseNumber: "CIV/1089/2022",
        petitioner: "பிரியா சிங்",
        respondent: "ஏபிசி கார்ப்பரேஷன்",
        invokedActs: ["நுகர்வோர் பாதுகாப்புச் சட்டம், 2019", "ஒப்பந்தச் சட்டம், 1872"],
        filingDate: "2022-11-02",
        lastHearingDate: "2024-06-10",
        complexityScore: 6.2,
        summary: "ஒப்பந்தத்தை மீறியதற்காகவும், குறைபாடுள்ள சேவைகளை வழங்கியதற்காகவும் பிரியா சிங் ஏபிசி கார்ப்பரேஷன் மீது தாக்கல் செய்த சிவில் வழக்கு. சேவை ஒப்பந்தத்தை நிறைவேற்றத் தவறியதால் ஏற்பட்ட நிதி இழப்பைக் கோருகிறார் மனுதாரர்.",
        pii: { "பிரியா சிங்": "[REDACTED_PERSON]" },
        priority: 'Medium',
        caseType: 'Civil',
    },
    {
        id: '3',
        title: "இந்திய யூனியன் vs. சுற்றுச்சூழல் ஆர்வலர்கள் குழு",
        caseNumber: "PIL/0045/2024",
        petitioner: "இந்திய யூனியன்",
        respondent: "சுற்றுச்சூழல் ஆர்வலர்கள் குழு",
        invokedActs: ["தேசிய பசுமை தீர்ப்பாயச் சட்டம், 2010", "சுற்றுச்சூழல் பாதுகாப்புச் சட்டம், 1986"],
        filingDate: "2024-02-10",
        lastHearingDate: "2024-07-01",
        complexityScore: 9.1,
        summary: "ஒரு பெரிய உள்கட்டமைப்பு திட்டத்திற்கான சுற்றுச்சூழல் அனுமதி தொடர்பான பொது நல வழக்கு (PIL). சாத்தியமான சூழலியல் பாதிப்பைக் காரணம் காட்டி, பிரதிவாதி குழு இந்த அனுமதிக்கு சவால் விடுத்துள்ளது.",
        priority: 'High',
        caseType: 'PIL',
    },
    {
        id: '4',
        title: "அஞ்சலி வர்மா vs. சுனில் வர்மா",
        caseNumber: "FAM/0312/2023",
        petitioner: "அஞ்சலி வர்மா",
        respondent: "சுனில் வர்மா",
        invokedActs: ["இந்து திருமணச் சட்டம், 1955", "குடும்ப வன்முறைச் சட்டம், 2005"],
        filingDate: "2023-08-25",
        lastHearingDate: "2024-06-28",
        complexityScore: 5.5,
        summary: "விவாகரத்து மற்றும் குடும்ப வன்முறை குற்றச்சாட்டுகள் தொடர்பான குடும்ப நீதிமன்ற வழக்கு. இந்த வழக்கில் குழந்தை காவல் மற்றும் ஜீவனாம்சம் தொடர்பான விஷயங்கள் அடங்கும்.",
        pii: { "அஞ்சலி வர்மா": "[REDACTED_PERSON]", "சுனில் வர்மா": "[REDACTED_PERSON]" },
        priority: 'Low',
        caseType: 'Divorce',
    },
];

const mockCasesTe: Case[] = [
    {
        id: '1',
        title: "మహారాష్ట్ర ప్రభుత్వం vs. రాజ్ శర్మ",
        caseNumber: "CR/0255/2023",
        petitioner: "మహారాష్ట్ర ప్రభుత్వం",
        respondent: "రాజ్ శర్మ",
        invokedActs: ["భారతీయ శిక్షాస్మృతి, 1860, సెక్షన్ 302", "ఆయుధాల చట్టం, 1959, సెక్షన్ 25"],
        filingDate: "2023-01-15",
        lastHearingDate: "2024-05-20",
        complexityScore: 8.5,
        summary: "హత్య మరియు అక్రమంగా ఆయుధాలు కలిగి ఉన్న ఆరోపణలతో కూడిన ఒక క్రిమినల్ కేసు. ప్రతివాది, రాజ్ శర్మ, ఒక ప్రాణాంతకమైన కాల్పుల్లో పాల్గొన్నాడని ప్రాసిక్యూషన్ ఆరోపిస్తుంది. ముఖ్యమైన సాక్ష్యాలలో ప్రత్యక్ష సాక్షుల వాంగ్మూలం మరియు ఫోరెన్సిక్ నివేదికలు ఉన్నాయి.",
        pii: { "రాజ్ శర్మ": "[REDACTED_PERSON]" },
        priority: 'High',
        caseType: 'Criminal',
    },
    {
        id: '2',
        title: "ప్రియా సింగ్ vs. ABC కార్పొరేషన్",
        caseNumber: "CIV/1089/2022",
        petitioner: "ప్రియా సింగ్",
        respondent: "ABC కార్పొరేషన్",
        invokedActs: ["వినియోగదారుల రక్షణ చట్టం, 2019", "ఒప్పంద చట్టం, 1872"],
        filingDate: "2022-11-02",
        lastHearingDate: "2024-06-10",
        complexityScore: 6.2,
        summary: "ఒప్పందాన్ని ఉల్లంఘించినందుకు మరియు లోపభూయిష్టమైన సేవలను అందించినందుకు ABC కార్పొరేషన్‌పై ప్రియా సింగ్ దాఖలు చేసిన సివిల్ దావా. సేవా ఒప్పందాన్ని నెరవేర్చడంలో ప్రతివాది వైఫల్యం కారణంగా పిటిషనర్ ఆర్థిక నష్టాలను క్లెయిమ్ చేశారు.",
        pii: { "ప్రియా సింగ్": "[REDACTED_PERSON]" },
        priority: 'Medium',
        caseType: 'Civil',
    },
    {
        id: '3',
        title: "యూనియన్ ఆఫ్ ఇండియా vs. పర్యావరణ కార్యకర్తల సమూహం",
        caseNumber: "PIL/0045/2024",
        petitioner: "యూనియన్ ఆఫ్ ఇండియా",
        respondent: "పర్యావరణ కార్యకర్తల సమూహం",
        invokedActs: ["నేషనల్ గ్రీన్ ట్రిబ్యునల్ చట్టం, 2010", "పర్యావరణ పరిరక్షణ చట్టం, 1986"],
        filingDate: "2024-02-10",
        lastHearingDate: "2024-07-01",
        complexityScore: 9.1,
        summary: "ఒక ప్రధాన మౌలిక సదుపాయాల ప్రాజెక్ట్ కోసం పర్యావరణ అనుమతికి సంబంధించిన ప్రజా ప్రయోజన వ్యాజ్యం (PIL). ప్రతివాది సమూహం పర్యావరణ నష్టాన్ని ఉటంకిస్తూ అనుమతిని సవాలు చేసింది.",
        priority: 'High',
        caseType: 'PIL',
    },
    {
        id: '4',
        title: "అంజలి వర్మ vs. సునీల్ వర్మ",
        caseNumber: "FAM/0312/2023",
        petitioner: "అంజలి వర్మ",
        respondent: "సునీల్ వర్మ",
        invokedActs: ["హిందూ వివాహ చట్టం, 1955", "గృహ హింస చట్టం, 2005"],
        filingDate: "2023-08-25",
        lastHearingDate: "2024-06-28",
        complexityScore: 5.5,
        summary: "విడాకుల కోసం పిటిషన్ మరియు గృహ హింస ఆరోపణలకు సంబంధించిన కుటుంబ న్యాయస్థానం కేసు. ఈ కేసులో పిల్లల అదుపు మరియు భరణం విషయాలు ఉన్నాయి.",
        pii: { "అంజలి వర్మ": "[REDACTED_PERSON]", "సునీల్ వర్మ": "[REDACTED_PERSON]" },
        priority: 'Low',
        caseType: 'Divorce',
    },
];

const mockCasesBn: Case[] = [
    {
        id: '1',
        title: "মহারাষ্ট্র রাজ্য বনাম রাজ শর্মা",
        caseNumber: "CR/0255/2023",
        petitioner: "মহারাষ্ট্র রাজ্য",
        respondent: "রাজ শর্মা",
        invokedActs: ["ভারতীয় দণ্ডবিধি, 1860, ধারা 302", "অস্ত্র আইন, 1959, ধারা 25"],
        filingDate: "2023-01-15",
        lastHearingDate: "2024-05-20",
        complexityScore: 8.5,
        summary: "হত্যা এবং অবৈধভাবে আগ্নেয়াস্ত্র রাখার অভিযোগ জড়িত একটি ফৌজদারি মামলা। প্রসিকিউশন অভিযোগ করেছে যে উত্তরদাতা, রাজ শর্মা, একটি মারাত্মক গুলি চালানোর ঘটনায় জড়িত ছিল। মূল প্রমাণের মধ্যে রয়েছে প্রত্যক্ষদর্শীর সাক্ষ্য এবং ফরেনসিক রিপোর্ট।",
        pii: { "রাজ শর্মা": "[REDACTED_PERSON]" },
        priority: 'High',
        caseType: 'Criminal',
    },
    {
        id: '2',
        title: "প্রিয়া সিং বনাম এবিসি কর্পোরেশন",
        caseNumber: "CIV/1089/2022",
        petitioner: "প্রিয়া সিং",
        respondent: "এবিসি কর্পোরেশন",
        invokedActs: ["ভোক্তা সুরক্ষা আইন, ২০১৯", "চুক্তি আইন, ১৮৭২"],
        filingDate: "2022-11-02",
        lastHearingDate: "2024-06-10",
        complexityScore: 6.2,
        summary: "চুক্তি লঙ্ঘন এবং ত্রুটিপূর্ণ পরিষেবা প্রদানের জন্য এবিসি কর্পোরেশনের বিরুদ্ধে প্রিয়া সিং দ্বারা দায়ের করা একটি দেওয়ানি মামলা। আবেদনকারী দাবি করেছেন যে উত্তরদাতার একটি পরিষেবা চুক্তি পূরণে ব্যর্থতার কারণে আর্থিক ক্ষতি হয়েছে।",
        pii: { "প্রিয়া সিং": "[REDACTED_PERSON]" },
        priority: 'Medium',
        caseType: 'Civil',
    },
    {
        id: '3',
        title: "ইউনিয়ন অফ ইন্ডিয়া বনাম পরিবেশ কর্মী গোষ্ঠী",
        caseNumber: "PIL/0045/2024",
        petitioner: "ইউনিয়ন অফ ইন্ডিয়া",
        respondent: "পরিবেশ কর্মী গোষ্ঠী",
        invokedActs: ["জাতীয় সবুজ ট্রাইব্যুনাল আইন, ২০১০", "পরিবেশ সুরক্ষা আইন, ১৯৮৬"],
        filingDate: "2024-02-10",
        lastHearingDate: "2024-07-01",
        complexityScore: 9.1,
        summary: "একটি বড় পরিকাঠামো প্রকল্পের জন্য পরিবেশগত ছাড়পত্র সংক্রান্ত একটি জনস্বার্থ মামলা (PIL)। উত্তরদাতা গোষ্ঠী সম্ভাব্য পরিবেশগত ক্ষতির কথা উল্লেখ করে ছাড়পত্রকে চ্যালেঞ্জ করেছে।",
        priority: 'High',
        caseType: 'PIL',
    },
    {
        id: '4',
        title: "অঞ্জলি ভার্মা বনাম সুনীল ভার্মা",
        caseNumber: "FAM/0312/2023",
        petitioner: "অঞ্জলি ভার্মা",
        respondent: "সুনীল ভার্মা",
        invokedActs: ["হিন্দু বিবাহ আইন, ১৯৫৫", "গার্হস্থ্য সহিংসতা আইন, ২০০৫"],
        filingDate: "2023-08-25",
        lastHearingDate: "2024-06-28",
        complexityScore: 5.5,
        summary: "বিবাহবিচ্ছেদের আবেদন এবং গার্হস্থ্য সহিংসতার অভিযোগ সংক্রান্ত একটি পারিবারিক আদালতের মামলা। এই মামলায় সন্তানের হেফাজত এবং ভরণপোষণের বিষয় জড়িত।",
        pii: { "অঞ্জলি ভার্মা": "[REDACTED_PERSON]", "সুনীল ভার্মা": "[REDACTED_PERSON]" },
        priority: 'Low',
        caseType: 'Divorce',
    },
];


export const getMockCases = (language: Language): Case[] => {
    switch (language) {
        case 'hi':
            return mockCasesHi;
        case 'ta':
            return mockCasesTa;
        case 'te':
            return mockCasesTe;
        case 'bn':
            return mockCasesBn;
        case 'en':
        default:
            return mockCasesEn;
    }
};

export const mockNpsData = [
  { name: 'Promoters', value: 400, fill: '#4CAF50' },
  { name: 'Passives', value: 300, fill: '#FFC107' },
  { name: 'Detractors', value: 100, fill: '#F44336' },
];